feat(workload): Add prototype support for workloads.
PolyJIT/benchbuild pull request #450
Opened 2021-11-01 23:24 UTC by simbuerg

This converts our implementation of workloads in the form of 'compile' and
'run_tests' into a generic support for workload functions.

The initial implementation aims for feature parity with our current behavior.
Therefore, we only add a 'Phase' enum to determine the execution time of the
workload.

Workloads are executed in insertion order, which is the order of definition in
the project.

A new workload is added by decorating a function with the 'phase' class
function.

This will be a breaking change.

2022-02-22 00:59 UTC, simbuerg commented
This still misses a sane way to support old ``compile`` and ``run_tests`` definitions properly.

2022-06-29 23:08 UTC, simbuerg commented
Still missing:

- Remove old draft implementation of workloads.
- More tests for Command/ProjectCommand, e.g. output_param
- SourceRoot detection without relying on source_of / accept relative dirs as relative to builddir.

2022-07-05 08:37 UTC, vulder requested changes
I'm still working on the full review, I just wanted to note a few things.

2022-07-05 08:37 UTC, vulder commented on benchbuild/project.py
> +            f_compile = run.in_builddir()(run.store_config(cls.run_tests))
```suggestion
            f_compile = run.in_builddir()(run.store_config(cls.compile))
```

2022-09-05 12:11 UTC, vulder commented on benchbuild/command.py
> +    index: WorkloadIndex, project: 'benchbuild.project.Project'
Why do we need to pass a index here? Can unwrap be used on another index?
Normally, `project.workloads` returns the index, which could be called inside unwrap, so we could only pass project and not both.

2022-09-05 13:30 UTC, vulder commented on benchbuild/command.py
> +class OnlyIn:
works like a charm :+1:

2022-09-13 05:40 UTC, merged